config {
    type: "table",
    description: "CTR event data with time request_paths of interest were completed unpivoted",
    columns: {
        session_id: "Pseudo-session based on anonymised user agent and IP",
        sign_in: "Date sign in request path was returned",
        searching: "Date search request path was returned",
        result_list: "Date result request path was returned",
        time_taken_seconds: "Time taken from search starting to the result list being produced",
        time_taken_sign_in_seconds: "Time taken from sign_in to the result list being produced"
    }
}

SELECT
  session_id,
  sign_in,
  searching,
  result_list,
  TIMESTAMP_DIFF(result_list, searching, SECOND) AS time_taken_seconds,
  TIMESTAMP_DIFF(result_list, sign_in, SECOND) AS time_taken_sign_in_seconds
FROM (
  SELECT
    anonymised_user_agent_and_ip AS session_id,
    request_path AS updated_request_path,
    occurred_at
  FROM
    ${ref("events_check_record")}
  WHERE request_path IN (
    '/check-records/sign-in', -- Not using this as the main start point because someone can sign in a day before starting their search
    '/check-records/search',  -- Use this as the journey start point
    '/check-records/result'   -- Use this as the journey end point
  )
)
PIVOT (
  MAX(occurred_at)
  FOR updated_request_path IN (
    '/check-records/sign-in' AS sign_in,
    '/check-records/search' AS searching,
    '/check-records/result' AS result_list
  )
)
WHERE result_list IS NOT NULL
ORDER BY
  time_taken_seconds DESC