config {
    type: "table",
    description: "CTR event data with time request_paths of interest were completed unpivoted",
    columns: {
        session_id: "Session id from session_details_check_record",
        sign_in: "Date sign in request path was returned",
        searching: "Date search request path was returned",
        result_list: "Date result request path was returned",
        time_taken_seconds: "Time taken from search starting to the result list being produced",
        time_taken_sign_in_seconds: "Time taken from sign_in to the result list being produced"
    }
}

SELECT
  session_id,
  sign_in,
  searching,
  result_list,
  TIMESTAMP_DIFF(result_list, searching, SECOND) AS time_taken_seconds,
  TIMESTAMP_DIFF(result_list, sign_in, SECOND) AS time_taken_sign_in_seconds
FROM (
  SELECT
    session_id,
    REGEXP_REPLACE(
      page.page,
      r".*/check-records/teachers.*",
      '/check-records/teachers'
    ) AS updated_request_path,
    page.page_entry_time AS occurred_at
  FROM
    ${ref("session_details_check_record")},
    UNNEST(pages_visited_details) AS page
  WHERE page.page IN (
    '/check-records/sign-in',
    '/check-records/search',
    '/check-records/result'
  )
)
PIVOT (
  MAX(occurred_at)
  FOR updated_request_path IN (
    '/check-records/sign-in' AS sign_in, -- Not using this as the main start point because someone can sign in a day before starting their search
    '/check-records/search' AS searching, -- Use this as the journey start point
    -- '/check-records/teachers' AS teacher,
    '/check-records/result' AS result_list -- Use this as the journey end point
  )
)
WHERE result_list IS NOT NULL
  AND searching IS NOT NULL
  AND result_list >= searching
  AND TIMESTAMP_DIFF(result_list, searching, SECOND) BETWEEN 0 AND 3600
ORDER BY
  time_taken_seconds DESC